module.exports = [
  {'name': '赵伟', 'img': '1.jpg', 'gender': '男', 'nickname': '赵', 'birthday': '1963-7-9', 'height': '183', 'email': 'zhao@gmail.com', 'tel': '156*****1987', 'hobby': '钢琴、书法、唱歌', 'address': '上海市黄浦区金陵东路569号17楼', 'job': '码农'},
  {'name': '李伟', 'img': '1.jpg', 'gender': '男', 'nickname': '李', 'birthday': '2003-12-7', 'height': '166', 'email': 'li@gmail.com', 'tel': '182*****1538', 'hobby': '钢琴、书法、唱歌', 'address': '上海市奉贤区南桥镇立新路12号2楼', 'job': '码农'},
  {'name': '孙伟', 'img': '1.jpg', 'gender': '女', 'nickname': '孙', 'birthday': '1993-12-7', 'height': '186', 'email': 'sun@gmail.com', 'tel': '161*****0097', 'hobby': '钢琴、书法、唱歌', 'address': '上海市崇明县城桥镇八一路739号', 'job': '码农'},
  {'name': '周伟', 'img': '1.jpg', 'gender': '女', 'nickname': '周', 'birthday': '1993-12-7', 'height': '188', 'email': 'zhou@gmail.com', 'tel': '197*****1123', 'hobby': '钢琴、书法、唱歌', 'address': '上海市青浦区青浦镇章浜路24号', 'job': '码农'},
  {'name': '吴伟', 'img': '1.jpg', 'gender': '男', 'nickname': '吴', 'birthday': '1993-12-7', 'height': '160', 'email': 'wu@gmail.com', 'tel': '183*****6678', 'hobby': '钢琴、书法、唱歌', 'address': '上海市松江区乐都西路867-871号', 'job': '码农'},
  {'name': '冯伟', 'img': '1.jpg', 'gender': '女', 'nickname': '冯', 'birthday': '1993-12-7', 'height': '168', 'email': 'feng@gmail.com', 'tel': '133*****3793', 'hobby': '钢琴、书法、唱歌', 'address': '上海市金山区龙胜路143号一层', 'job': '码农'},
  {'name': '褚伟', 'img': '1.jpg', 'gender': '男', 'nickname': '褚', 'birthday': '1993-12-7', 'height': '170', 'email': 'zhu@gmail.com', 'tel': '189*****2345', 'hobby': '钢琴、书法、唱歌', 'address': '上海市闵行区都市路2988号2楼', 'job': '码农'},
  {'name': '蒋伟', 'img': '1.jpg', 'gender': '女', 'nickname': '蒋', 'birthday': '1993-12-7', 'height': '178', 'email': 'jiang@gmail.com', 'tel': '166*****2267', 'hobby': '钢琴、书法、唱歌', 'address': '上海市浦东新区惠南镇人民西路85号建行大楼2楼', 'job': '码农'},
  {'name': '韩伟', 'img': '1.jpg', 'gender': '女', 'nickname': '韩', 'birthday': '1993-12-7', 'height': '166', 'email': 'han@gmail.com', 'tel': '177*****2222', 'hobby': '钢琴、书法、唱歌', 'address': '上海市浦东新区东方路818号建行一楼', 'job': '码农'},
  {'name': '秦伟', 'img': '1.jpg', 'gender': '男', 'nickname': '秦', 'birthday': '1893-12-6', 'height': '175', 'email': 'qin@gmail.com', 'tel': '187*****9999', 'hobby': '钢琴、书法、唱歌', 'address': '上海市浦东新区浦城路812号2楼', 'job': '码农'}]
